name: des_rt_v
channels:
  - defaults
dependencies:
  - python=3.11.9
  - ipykernel
  - pip:
    - simpy==4.0.2
    - matplotlib==3.9.1.post1
    - numpy==1.26.4
    - pandas==2.2.2
    - plotly==5.23.0
    - sim-tools==0.6.1
    - vidigi==0.0.4
    - streamlit==1.37.0
    - streamlit_folium==0.22.0
